import type { DocumentRef, QmsState } from "./types";
import { nowIso, shiftDays } from "./utils";

function seedDoc(id: string, name: string, size: number, mimeType: string, uploadedBy: string, category?: string): DocumentRef {
  return { id, name, size, mimeType, uploadedAt: nowIso(), uploadedBy, category, seeded: true };
}

export function createInitialState(): QmsState {
  return {
    employees: [
      {
        id: "emp-1",
        employeeId: "EMP-1001",
        name: "Ananya Sharma",
        department: "Quality Assurance",
        email: "ananya.sharma@northwind-labs.com",
        jobRole: "QA Engineer",
        reportsTo: "emp-4",
        status: "Active",
        createdAt: nowIso(),
      },
      {
        id: "emp-2",
        employeeId: "EMP-1002",
        name: "Rahul Verma",
        department: "Production",
        email: "rahul.verma@northwind-labs.com",
        jobRole: "Line Supervisor",
        reportsTo: "emp-4",
        status: "Active",
        createdAt: nowIso(),
      },
      {
        id: "emp-3",
        employeeId: "EMP-1003",
        name: "Meera Iyer",
        department: "Regulatory Affairs",
        email: "meera.iyer@northwind-labs.com",
        jobRole: "Regulatory Specialist",
        reportsTo: "emp-5",
        status: "Active",
        createdAt: nowIso(),
      },
      {
        id: "emp-4",
        employeeId: "EMP-1004",
        name: "Daniel Okoro",
        department: "Quality Assurance",
        email: "daniel.okoro@northwind-labs.com",
        jobRole: "Quality Manager",
        status: "Active",
        createdAt: nowIso(),
      },
      {
        id: "emp-5",
        employeeId: "EMP-1005",
        name: "Sofia Almeida",
        department: "Operations",
        email: "sofia.almeida@northwind-labs.com",
        jobRole: "Operations Director",
        status: "Active",
        createdAt: nowIso(),
      },
      {
        id: "emp-6",
        employeeId: "EMP-1006",
        name: "Tobias Krause",
        department: "Engineering",
        email: "tobias.krause@northwind-labs.com",
        jobRole: "Maintenance Technician",
        reportsTo: "emp-5",
        status: "Active",
        createdAt: nowIso(),
      },
      {
        id: "emp-7",
        employeeId: "EMP-1007",
        name: "Priya Nair",
        department: "Warehouse",
        email: "priya.nair@northwind-labs.com",
        jobRole: "Inventory Lead",
        reportsTo: "emp-5",
        status: "Inactive",
        createdAt: nowIso(),
      },
    ],

    courses: [
      {
        id: "crs-1",
        code: "TRN-GMP-01",
        title: "Good Manufacturing Practice Refresher",
        description: "Annual refresher on GMP hygiene, documentation and deviation handling.",
        frequency: "Annual",
        durationHours: 4,
        status: "Active",
        createdAt: nowIso(),
      },
      {
        id: "crs-2",
        code: "TRN-SOP-14",
        title: "SOP-14 Document Control",
        description: "Controlled document lifecycle, revision numbering and archival rules.",
        frequency: "Quarterly",
        durationHours: 2,
        status: "Active",
        createdAt: nowIso(),
      },
      {
        id: "crs-3",
        code: "TRN-SAF-07",
        title: "Machine Safety & Lockout-Tagout",
        description: "Energy isolation procedures for production equipment.",
        frequency: "Half-Yearly",
        durationHours: 3,
        status: "Active",
        createdAt: nowIso(),
      },
      {
        id: "crs-4",
        code: "TRN-ISO-9001",
        title: "ISO 9001:2015 Internal Auditor",
        description: "Clause-by-clause walkthrough and internal audit technique.",
        frequency: "Annual",
        durationHours: 8,
        status: "Active",
        createdAt: nowIso(),
      },
      {
        id: "crs-5",
        code: "TRN-LEG-03",
        title: "Legacy Data Integrity Module",
        description: "Retired in favour of TRN-GMP-01. Kept for historical records.",
        frequency: "One-Time",
        durationHours: 1,
        status: "Inactive",
        createdAt: nowIso(),
      },
    ],

    assignments: [
      {
        id: "asg-1",
        courseId: "crs-1",
        employeeId: "emp-1",
        assignedBy: "Daniel Okoro",
        startDate: shiftDays(-12),
        dueDate: shiftDays(6),
        status: "In Progress",
        startedAt: nowIso(),
        documents: [],
        history: [
          { id: "hist-1", at: nowIso(), actor: "Daniel Okoro", action: "Assigned" },
          { id: "hist-2", at: nowIso(), actor: "Ananya Sharma", action: "Started training" },
        ],
      },
      {
        id: "asg-2",
        courseId: "crs-2",
        employeeId: "emp-1",
        assignedBy: "Daniel Okoro",
        startDate: shiftDays(-30),
        dueDate: shiftDays(-3),
        status: "Waiting for Approval",
        startedAt: nowIso(),
        submittedAt: nowIso(),
        documents: [
          seedDoc("doc-seed-1", "SOP-14-assessment-signed.pdf", 284_512, "application/pdf", "Ananya Sharma", "Completion certificate"),
        ],
        history: [
          { id: "hist-3", at: nowIso(), actor: "Daniel Okoro", action: "Assigned" },
          { id: "hist-4", at: nowIso(), actor: "Ananya Sharma", action: "Started training" },
          { id: "hist-5", at: nowIso(), actor: "Ananya Sharma", action: "Submitted for review", note: "Assessment sheet attached." },
        ],
      },
      {
        id: "asg-3",
        courseId: "crs-3",
        employeeId: "emp-2",
        assignedBy: "Daniel Okoro",
        startDate: shiftDays(-5),
        dueDate: shiftDays(14),
        status: "Pending",
        documents: [],
        history: [{ id: "hist-6", at: nowIso(), actor: "Daniel Okoro", action: "Assigned" }],
      },
      {
        id: "asg-4",
        courseId: "crs-4",
        employeeId: "emp-3",
        assignedBy: "Sofia Almeida",
        startDate: shiftDays(-60),
        dueDate: shiftDays(-20),
        status: "Approved",
        startedAt: nowIso(),
        submittedAt: nowIso(),
        reviewedAt: nowIso(),
        reviewedBy: "Sofia Almeida",
        reviewComments: "Audit log walkthrough demonstrated competence. Approved.",
        score: 92,
        documents: [
          seedDoc("doc-seed-2", "iso9001-auditor-certificate.pdf", 512_000, "application/pdf", "Meera Iyer", "Completion certificate"),
        ],
        history: [
          { id: "hist-7", at: nowIso(), actor: "Sofia Almeida", action: "Assigned" },
          { id: "hist-8", at: nowIso(), actor: "Meera Iyer", action: "Submitted for review" },
          { id: "hist-9", at: nowIso(), actor: "Sofia Almeida", action: "Approved", note: "Score 92%" },
        ],
      },
      {
        id: "asg-5",
        courseId: "crs-1",
        employeeId: "emp-2",
        assignedBy: "Daniel Okoro",
        startDate: shiftDays(-45),
        dueDate: shiftDays(-15),
        status: "Rejected",
        startedAt: nowIso(),
        submittedAt: nowIso(),
        reviewedAt: nowIso(),
        reviewedBy: "Daniel Okoro",
        reviewComments: "Attached certificate was illegible. Please re-upload a clear scan.",
        documents: [],
        history: [
          { id: "hist-10", at: nowIso(), actor: "Daniel Okoro", action: "Assigned" },
          { id: "hist-11", at: nowIso(), actor: "Rahul Verma", action: "Submitted for review" },
          { id: "hist-12", at: nowIso(), actor: "Daniel Okoro", action: "Rejected", note: "Illegible evidence" },
        ],
      },
      {
        id: "asg-6",
        courseId: "crs-2",
        employeeId: "emp-6",
        assignedBy: "Daniel Okoro",
        startDate: shiftDays(-2),
        dueDate: shiftDays(9),
        status: "Waiting for Approval",
        startedAt: nowIso(),
        submittedAt: nowIso(),
        documents: [
          seedDoc("doc-seed-3", "doc-control-quiz-result.png", 96_240, "image/png", "Tobias Krause", "Assessment result"),
        ],
        history: [
          { id: "hist-13", at: nowIso(), actor: "Daniel Okoro", action: "Assigned" },
          { id: "hist-14", at: nowIso(), actor: "Tobias Krause", action: "Submitted for review" },
        ],
      },
    ],

    assets: [
      {
        id: "ast-1",
        serialNumber: "MCH-AC-8841",
        name: "Autoclave Sterilizer A1",
        category: "Sterilization",
        location: "Block B / Clean Room 2",
        manufacturer: "SteriTech",
        ppmStartDate: shiftDays(-90),
        dueDate: shiftDays(4),
        frequency: "Quarterly",
        maintenanceState: "Due Soon",
        status: "Active",
        documents: [
          seedDoc("doc-seed-4", "autoclave-inspection-Q3.pdf", 733_184, "application/pdf", "Tobias Krause", "Inspection report"),
        ],
        createdAt: nowIso(),
      },
      {
        id: "ast-2",
        serialNumber: "MCH-FL-2210",
        name: "Vial Filling Line 2",
        category: "Production",
        location: "Block A / Filling Hall",
        manufacturer: "Optima",
        ppmStartDate: shiftDays(-180),
        dueDate: shiftDays(-6),
        frequency: "Half-Yearly",
        maintenanceState: "Overdue",
        status: "Active",
        documents: [
          seedDoc("doc-seed-5", "filling-line-2-service-log.xlsx", 45_120, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Tobias Krause", "Service log"),
        ],
        createdAt: nowIso(),
      },
      {
        id: "ast-3",
        serialNumber: "MCH-HV-0317",
        name: "HVAC Air Handling Unit 3",
        category: "Facilities",
        location: "Roof / AHU Deck",
        manufacturer: "Carrier",
        ppmStartDate: shiftDays(-30),
        dueDate: shiftDays(60),
        frequency: "Quarterly",
        maintenanceState: "Scheduled",
        status: "Active",
        documents: [],
        createdAt: nowIso(),
      },
      {
        id: "ast-4",
        serialNumber: "MCH-BL-5509",
        name: "Analytical Balance XP205",
        category: "Laboratory",
        location: "QC Lab / Bench 4",
        manufacturer: "Mettler Toledo",
        ppmStartDate: shiftDays(-20),
        dueDate: shiftDays(10),
        frequency: "Monthly",
        maintenanceState: "In Progress",
        status: "Active",
        documents: [
          seedDoc("doc-seed-6", "balance-calibration-cert.pdf", 210_944, "application/pdf", "Ananya Sharma", "Calibration certificate"),
        ],
        createdAt: nowIso(),
      },
      {
        id: "ast-5",
        serialNumber: "MCH-CP-1102",
        name: "Legacy Capping Machine",
        category: "Production",
        location: "Store / Decommissioned",
        manufacturer: "Groninger",
        ppmStartDate: shiftDays(-400),
        dueDate: shiftDays(-120),
        frequency: "Annual",
        maintenanceState: "Completed",
        status: "Inactive",
        documents: [],
        createdAt: nowIso(),
      },
    ],

    maintenanceRequests: [
      {
        id: "mrq-1",
        assetId: "ast-2",
        type: "Corrective",
        raisedBy: "Rahul Verma",
        technician: "Tobias Krause",
        scheduledDate: shiftDays(-6),
        description: "Filling nozzle 4 dripping during changeover, volume variance above tolerance.",
        status: "In Progress",
        findings: "Worn seal kit identified; replacement ordered.",
        downtimeHours: 5,
        documents: [],
        createdAt: nowIso(),
      },
      {
        id: "mrq-2",
        assetId: "ast-1",
        type: "Preventive",
        raisedBy: "Daniel Okoro",
        technician: "Tobias Krause",
        scheduledDate: shiftDays(4),
        description: "Quarterly chamber gasket inspection and vacuum leak test.",
        status: "Open",
        documents: [],
        createdAt: nowIso(),
      },
      {
        id: "mrq-3",
        assetId: "ast-4",
        type: "Calibration",
        raisedBy: "Ananya Sharma",
        technician: "External - Mettler Service",
        scheduledDate: shiftDays(-2),
        completedDate: shiftDays(-1),
        description: "Monthly calibration with certified E2 weight set.",
        findings: "All points within 0.02 mg tolerance. Certificate issued.",
        downtimeHours: 1,
        status: "Completed",
        documents: [
          seedDoc("doc-seed-7", "balance-cal-run-sheet.pdf", 118_784, "application/pdf", "Ananya Sharma", "Maintenance record"),
        ],
        createdAt: nowIso(),
      },
      {
        id: "mrq-4",
        assetId: "ast-3",
        type: "Routine",
        raisedBy: "Sofia Almeida",
        technician: "Facilities Crew",
        scheduledDate: shiftDays(12),
        description: "HEPA filter differential pressure check and pre-filter swap.",
        status: "Open",
        documents: [],
        createdAt: nowIso(),
      },
    ],

    suppliers: [
      {
        id: "sup-1",
        name: "Mettler Toledo Service India",
        department: "Quality Control",
        serviceSupplied: true,
        contactPerson: "Vikram Rao",
        phone: "+91 98200 44112",
        email: "service.in@mettler.example",
        dueDate: shiftDays(21),
        rating: 4.6,
        status: "Active",
        createdAt: nowIso(),
      },
      {
        id: "sup-2",
        name: "Schott Glass Packaging",
        department: "Procurement",
        serviceSupplied: false,
        contactPerson: "Lena Fischer",
        phone: "+49 6131 66123",
        email: "lena.fischer@schott.example",
        dueDate: shiftDays(-4),
        rating: 4.1,
        status: "Active",
        createdAt: nowIso(),
      },
      {
        id: "sup-3",
        name: "CleanRoom Care Services",
        department: "Facilities",
        serviceSupplied: true,
        contactPerson: "Joseph Mathew",
        phone: "+91 80456 77219",
        email: "ops@cleanroomcare.example",
        dueDate: shiftDays(9),
        rating: 3.8,
        status: "Active",
        createdAt: nowIso(),
      },
      {
        id: "sup-4",
        name: "Northline Logistics",
        department: "Warehouse",
        serviceSupplied: true,
        contactPerson: "Aarti Desai",
        phone: "+91 22615 90088",
        email: "dispatch@northline.example",
        dueDate: shiftDays(45),
        rating: 4.4,
        status: "Active",
        createdAt: nowIso(),
      },
      {
        id: "sup-5",
        name: "Apex Calibration Co.",
        department: "Engineering",
        serviceSupplied: true,
        contactPerson: "Suresh Menon",
        phone: "+91 44287 33410",
        email: "contact@apexcal.example",
        dueDate: shiftDays(-90),
        rating: 2.9,
        status: "Inactive",
        createdAt: nowIso(),
      },
    ],

    projects: [
      {
        id: "prj-1",
        code: "PRJ-QMS-01",
        name: "QMS Digital Transformation",
        owner: "Sofia Almeida",
        description: "Replace paper-based quality records with the digital QMS platform across all sites.",
        startDate: shiftDays(-60),
        expectedCompletionDate: shiftDays(120),
        status: "Active",
        createdAt: nowIso(),
      },
      {
        id: "prj-2",
        code: "PRJ-ISO-02",
        name: "ISO 13485 Certification Readiness",
        owner: "Daniel Okoro",
        description: "Gap assessment, remediation and stage-1 audit preparation for ISO 13485.",
        startDate: shiftDays(-20),
        expectedCompletionDate: shiftDays(200),
        status: "Active",
        createdAt: nowIso(),
      },
      {
        id: "prj-3",
        code: "PRJ-ARC-03",
        name: "Archive Migration (2019-2021)",
        owner: "Meera Iyer",
        description: "Closed out. Retained for historical reporting only.",
        startDate: shiftDays(-500),
        expectedCompletionDate: shiftDays(-200),
        status: "Inactive",
        createdAt: nowIso(),
      },
    ],

    phases: [
      {
        id: "phs-1",
        projectId: "prj-1",
        name: "Requirement Gathering Phase",
        description: "Workshops with quality, production and regulatory stakeholders.",
        startDate: shiftDays(-60),
        endDate: shiftDays(-20),
        status: "Active",
        createdAt: nowIso(),
      },
      {
        id: "phs-2",
        projectId: "prj-1",
        name: "Design & Configuration Phase",
        description: "Module blueprints, role matrix and workflow configuration.",
        startDate: shiftDays(-19),
        endDate: shiftDays(30),
        status: "Active",
        createdAt: nowIso(),
      },
      {
        id: "phs-3",
        projectId: "prj-1",
        name: "Validation & Go-Live Phase",
        description: "IQ/OQ/PQ execution, training rollout and hypercare.",
        startDate: shiftDays(31),
        endDate: shiftDays(120),
        status: "Active",
        createdAt: nowIso(),
      },
      {
        id: "phs-4",
        projectId: "prj-2",
        name: "Gap Assessment Phase",
        description: "Clause-level gap analysis against ISO 13485:2016.",
        startDate: shiftDays(-20),
        endDate: shiftDays(40),
        status: "Active",
        createdAt: nowIso(),
      },
    ],

    milestones: [
      {
        id: "mls-1",
        phaseId: "phs-1",
        name: "Discuss Requirements with Client",
        description: "Signed-off requirement register from all departments.",
        dueDate: shiftDays(-40),
        completed: true,
        createdAt: nowIso(),
      },
      {
        id: "mls-2",
        phaseId: "phs-1",
        name: "Baseline URS Approved",
        description: "User requirement specification approved by QA head.",
        dueDate: shiftDays(-22),
        completed: true,
        createdAt: nowIso(),
      },
      {
        id: "mls-3",
        phaseId: "phs-2",
        name: "Workflow Blueprint Sign-off",
        description: "Training and PPM approval routes agreed.",
        dueDate: shiftDays(7),
        completed: false,
        createdAt: nowIso(),
      },
      {
        id: "mls-4",
        phaseId: "phs-2",
        name: "Role & Permission Matrix Locked",
        description: "Employee / Manager / Admin capability matrix frozen.",
        dueDate: shiftDays(24),
        completed: false,
        createdAt: nowIso(),
      },
      {
        id: "mls-5",
        phaseId: "phs-3",
        name: "Validation Protocol Executed",
        description: "IQ/OQ/PQ dossier complete with deviations closed.",
        dueDate: shiftDays(95),
        completed: false,
        createdAt: nowIso(),
      },
      {
        id: "mls-6",
        phaseId: "phs-4",
        name: "Clause Gap Register Published",
        description: "All non-conformities logged with owners.",
        dueDate: shiftDays(18),
        completed: false,
        createdAt: nowIso(),
      },
    ],

    tasks: [
      {
        id: "tsk-1",
        milestoneId: "mls-1",
        title: "Run QA department workshop",
        description: "Two-hour session covering training and audit pain points.",
        assigneeId: "emp-1",
        dueDate: shiftDays(-45),
        status: "Completed",
        createdAt: nowIso(),
      },
      {
        id: "tsk-2",
        milestoneId: "mls-1",
        title: "Consolidate requirement register",
        description: "Merge workshop outputs into a single traceable register.",
        assigneeId: "emp-3",
        dueDate: shiftDays(-41),
        status: "Completed",
        createdAt: nowIso(),
      },
      {
        id: "tsk-3",
        milestoneId: "mls-3",
        title: "Draft training approval workflow",
        description: "Submit → review → approve/reject with comment capture.",
        assigneeId: "emp-1",
        dueDate: shiftDays(3),
        status: "In Progress",
        createdAt: nowIso(),
      },
      {
        id: "tsk-4",
        milestoneId: "mls-3",
        title: "Map PPM reminder triggers",
        description: "Define 1-week and 2-week advance reminder rules.",
        assigneeId: "emp-6",
        dueDate: shiftDays(5),
        status: "To Do",
        createdAt: nowIso(),
      },
      {
        id: "tsk-5",
        milestoneId: "mls-4",
        title: "Review permission matrix with IT security",
        description: "Confirm least-privilege alignment for the admin role.",
        assigneeId: "emp-5",
        dueDate: shiftDays(20),
        status: "Blocked",
        createdAt: nowIso(),
      },
      {
        id: "tsk-6",
        milestoneId: "mls-6",
        title: "Audit clause 7.5 documented information",
        description: "Compare current SOP set against clause requirements.",
        assigneeId: "emp-3",
        dueDate: shiftDays(12),
        status: "In Progress",
        createdAt: nowIso(),
      },
    ],

    audits: [
      {
        id: "aud-1",
        processName: "Operations Management",
        responsibility: "Operations Director",
        clauses: ["4.4", "8.1", "9.1.3"],
        inputs: "Production plan, resource availability, customer forecast, batch records",
        activities:
          "Capacity planning, shift scheduling, line clearance verification, in-process monitoring, deviation escalation",
        outputs: "Released batches, OEE report, deviation log, monthly operations review deck",
        solidData: "OEE dashboard export, shift handover logs, deviation register QMS-DEV-2024",
        auditors: ["Daniel Okoro", "Ananya Sharma"],
        auditDate: shiftDays(8),
        status: "Active",
        createdAt: nowIso(),
      },
      {
        id: "aud-2",
        processName: "Document & Record Control",
        responsibility: "Regulatory Specialist",
        clauses: ["7.5.1", "7.5.2", "7.5.3"],
        inputs: "Change requests, draft SOPs, obsolete document list",
        activities: "Draft review, approval routing, distribution, periodic review, archival",
        outputs: "Effective controlled documents, training triggers, obsolete stamps",
        solidData: "Document master list, revision history report",
        auditors: ["Meera Iyer"],
        auditDate: shiftDays(-14),
        status: "Active",
        createdAt: nowIso(),
      },
      {
        id: "aud-3",
        processName: "Legacy Vendor Qualification",
        responsibility: "Procurement Lead",
        clauses: ["8.4"],
        inputs: "Vendor questionnaires",
        activities: "Desk audits only",
        outputs: "Approved vendor list v1",
        solidData: "Archived questionnaires",
        auditors: ["Sofia Almeida"],
        auditDate: shiftDays(-240),
        status: "Inactive",
        createdAt: nowIso(),
      },
    ],

    subProcesses: [
      {
        id: "sub-1",
        auditId: "aud-1",
        name: "Production Scheduling",
        responsibility: "Operations Director",
        inputs: "Production plan, resource availability, customer forecast, batch records",
        activities: "Weekly capacity levelling, changeover sequencing, bottleneck review",
        outputs: "Released batches, OEE report, deviation log, monthly operations review deck",
        kpis: [
          { id: "kpi-1", name: "Schedule Adherence", unit: "%", target: 95, actual: 91.4, period: "Q3" },
          { id: "kpi-2", name: "Changeover Time", unit: "min", target: 45, actual: 52, period: "Q3" },
          { id: "kpi-3", name: "Plan Revisions per Week", unit: "count", target: 2, actual: 1.6, period: "Q3" },
        ],
        clauseChecks: [
          {
            id: "clc-1",
            clause: "4.4",
            requirement: "Process interactions determined and monitored with defined criteria.",
            verdict: "Compliant",
            notes: "Process map QMS-PM-002 current and signed.",
          },
          {
            id: "clc-2",
            clause: "8.1",
            requirement: "Operational planning and control criteria documented.",
            verdict: "Minor NC",
            notes: "Changeover sequencing rules not reflected in SOP-22 revision 4.",
          },
        ],
        evidence: [
          seedDoc("doc-seed-8", "oee-dashboard-Q3.pdf", 640_000, "application/pdf", "Daniel Okoro", "KPI evidence"),
          seedDoc("doc-seed-9", "shift-handover-week34.jpg", 1_204_224, "image/jpeg", "Rahul Verma", "Clause 8.1 evidence"),
        ],
        evaluation: null,
        createdAt: nowIso(),
      },
      {
        id: "sub-2",
        auditId: "aud-1",
        name: "In-Process Quality Monitoring",
        responsibility: "Operations Director",
        inputs: "Production plan, resource availability, customer forecast, batch records",
        activities: "Hourly checks, control chart review, out-of-trend escalation",
        outputs: "Released batches, OEE report, deviation log, monthly operations review deck",
        kpis: [
          { id: "kpi-4", name: "First Pass Yield", unit: "%", target: 98, actual: 98.7, period: "Q3" },
          { id: "kpi-5", name: "Open Deviations > 30d", unit: "count", target: 0, actual: 2, period: "Q3" },
        ],
        clauseChecks: [
          {
            id: "clc-3",
            clause: "9.1.3",
            requirement: "Analysis and evaluation of monitoring data.",
            verdict: "Compliant",
            notes: "Control charts reviewed in monthly quality council.",
          },
        ],
        evidence: [],
        evaluation: {
          comments:
            "Monitoring is effective; two ageing deviations need a closure plan before the next review cycle.",
          score: 78,
          approved: true,
          evaluatedBy: "Daniel Okoro",
          evaluatedAt: nowIso(),
        },
        createdAt: nowIso(),
      },
      {
        id: "sub-3",
        auditId: "aud-2",
        name: "Periodic Document Review",
        responsibility: "Regulatory Specialist",
        inputs: "Change requests, draft SOPs, obsolete document list",
        activities: "Review-due report generation, owner follow-up, revision issuance",
        outputs: "Effective controlled documents, training triggers, obsolete stamps",
        kpis: [
          { id: "kpi-6", name: "Documents Overdue for Review", unit: "count", target: 0, actual: 5, period: "Q3" },
        ],
        clauseChecks: [
          {
            id: "clc-4",
            clause: "7.5.2",
            requirement: "Documented information appropriately identified and approved.",
            verdict: "Major NC",
            notes: "Five SOPs past their two-year review date remained effective.",
          },
        ],
        evidence: [],
        evaluation: null,
        createdAt: nowIso(),
      },
    ],

    reminders: [
      {
        id: "rem-1",
        module: "Training",
        event: "Training due date approaching",
        leadDays: 14,
        channel: "Email",
        recipients: "Assignee",
        enabled: true,
      },
      {
        id: "rem-2",
        module: "Training",
        event: "Training due date approaching",
        leadDays: 7,
        channel: "Email + In-App",
        recipients: "Assignee, Reporting Manager",
        enabled: true,
      },
      {
        id: "rem-3",
        module: "Training",
        event: "Submission waiting for approval",
        leadDays: 2,
        channel: "In-App",
        recipients: "Reporting Manager",
        enabled: true,
      },
      {
        id: "rem-4",
        module: "PPM",
        event: "Preventive maintenance due date approaching",
        leadDays: 14,
        channel: "Email",
        recipients: "Maintenance Technician, Engineering Head",
        enabled: true,
      },
      {
        id: "rem-5",
        module: "PPM",
        event: "Preventive maintenance due date approaching",
        leadDays: 7,
        channel: "Email + In-App",
        recipients: "Maintenance Technician, Plant Manager",
        enabled: true,
      },
      {
        id: "rem-6",
        module: "Supplier",
        event: "Supplier re-qualification due",
        leadDays: 30,
        channel: "Email",
        recipients: "Procurement Lead",
        enabled: false,
      },
      {
        id: "rem-7",
        module: "Audit",
        event: "Scheduled audit date approaching",
        leadDays: 7,
        channel: "Email + In-App",
        recipients: "Assigned Auditors, Process Owner",
        enabled: true,
      },
    ],

    session: {
      role: "System Admin",
      employeeId: "emp-1",
    },
  };
}
